#!/usr/bin/env node
// Generates "Daily Coder Vivid" from the default theme.
//
// Both palettes in colors.ts share one luminance ladder, so swapping every color for the same
// family and shade of `vividPalette` keeps every contrast of the default theme and only raises
// chroma. Edit the default theme, then run this; never edit the vivid theme by hand.
//
// Usage: node scripts/build-vivid.mjs

import fs from "node:fs";
import { fileURLToPath } from "node:url";

const root = (file) => fileURLToPath(new URL(`../${file}`, import.meta.url));
const SOURCE = root("themes/Daily Coder-color-theme.json");
const TARGET = root("themes/Daily Coder Vivid-color-theme.json");

function fail(message) {
    console.error(`build-vivid: ${message}`);
    process.exit(1);
}

// Reads `export const <name> = { family: { shade: "#hex", ... }, ... }` from colors.ts.
function readPalette(src, name) {
    const start = src.indexOf(`export const ${name} = {`);
    if (start < 0) fail(`colors.ts has no \`${name}\`.`);
    const body = src.slice(start, src.indexOf("} as const;", start));
    const palette = {};
    let family = null;
    for (const line of body.split("\n").slice(1)) {
        const open = line.match(/^\s{4}(\w+): \{/);
        const shade = line.match(/^\s{8}(\d+): "(#[0-9a-f]{6})"/i);
        if (open) palette[(family = open[1])] = {};
        else if (shade && family) palette[family][shade[1]] = shade[2].toLowerCase();
    }
    return palette;
}

const colors = fs.readFileSync(root("colors.ts"), "utf8");
const base = readPalette(colors, "palette");
const vivid = readPalette(colors, "vividPalette");

const swap = new Map();
for (const [family, shades] of Object.entries(base)) {
    for (const [shade, hex] of Object.entries(shades)) {
        const target = vivid[family]?.[shade];
        if (!target) fail(`vividPalette is missing ${family} ${shade}.`);
        if (swap.has(hex) && swap.get(hex) !== target)
            fail(`${hex} appears twice in palette with different vivid values.`);
        swap.set(hex, target);
    }
}

const unknown = new Set();
const theme = fs
    .readFileSync(SOURCE, "utf8")
    .replace(/"(#[0-9a-f]{6})([0-9a-f]{2})?"/gi, (match, hex, alpha = "") => {
        const key = hex.toLowerCase();
        if (key === "#000000") return match;
        if (!swap.has(key)) {
            unknown.add(hex);
            return match;
        }
        return `"${swap.get(key)}${alpha}"`;
    })
    .replace('"name": "Daily Coder",', '"name": "Daily Coder Vivid",')
    .replace(
        '"colors": {',
        '"colors": {\n        // Generated by `npm run build:vivid` from Daily Coder-color-theme.json. Do not edit by hand.'
    );

if (unknown.size)
    fail(`colors outside the palette: ${[...unknown].join(", ")}. Use palette colors only.`);

fs.writeFileSync(TARGET, theme);
console.log(`Wrote ${TARGET}`);
